version: "2"

services:

  web:
    build:
      context: .
    restart: "always"
    env_file: ".env"
    links:
      - "postgres"
      - "elasticsearch"
      - "logstash"

  elasticsearch:
    build: "services/elasticsearch"
    restart: "always"
    volumes:
      - "./data/elasticsearch/data:/usr/share/elasticsearch/data"
      - "./data/elasticsearch/log:/usr/share/elasticsearch/log"

  logstash:
    image: "logstash"
    restart: "always"
    links:
      - "elasticsearch"
    command: "logstash -f /etc/logstash/conf.d/ --allow-env"
    volumes:
      - "./conf/logstash:/etc/logstash/conf.d"

  kibana:
    image: "kibana"
    restart: "always"
    links:
      - "elasticsearch"

  postgres:
    image: "postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "sundog_db"
      POSTGRES_USER: "sundog_db"
      POSTGRES_PASSWORD: "sundog_db"
    volumes:
      - "./data/postgres/data:/var/lib/postgresql/data"
      - "./data/postgres/log:/var/log/postgresql"
