version: "2"

services:

  web:
    build: .
    links:
      - postgres
      - elasticsearch
      - logstash
    environment:
      DEBUG: 'true'
    restart: always

  elasticsearch:
    image: "elasticsearch"
    volumes:
      - "./data/elasticsearch/data:/usr/share/elasticsearch/data"
      - "./data/elasticsearch/log:/usr/share/elasticsearch/log"

  logstash:
    image: "logstash"
    links:
      - "elasticsearch"
    command: "logstash -f /etc/logstash/conf.d/"
    volumes:
      - "./conf/logstash:/etc/logstash/conf.d"

  kibana:
    image: "kibana"
    links:
      - "elasticsearch"

  postgres:
    image: "postgres"
    environment:
      POSTGRES_DB: "sundog_db"
      POSTGRES_USER: "sundog_db"
      POSTGRES_PASSWORD: "sundog_db"
    volumes:
      - "./data/postgres/data:/var/lib/postgresql/data"
      - "./data/postgres/log:/var/log/postgresql"
