version: "2"

services:

  web:
    extends:
      file: docker-compose.yml
      service: web
    environment:
      DEBUG: "False"

  haproxy:
    image: "bradjonesllc/docker-haproxy-letsencrypt"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - "web:www"
    environment:
      POSTGRES_DB: "sundog_db"
      CERTS: "52.38.185.134.nip.io"
      EMAIL: "mgomez@mahisoft.com"
    volumes:
      - "./data/letsencrypt:/etc/letsencrypt"
